return value of method call can be object
js-soft/wdi5 pull request #234
Opened 2022-04-13 13:13 UTC by dominikfeininger

- still basic implementation
- to discuss: best way of remove circular
- todo: add tests to prove

for #224

2022-04-14 12:24 UTC, dominikfeininger commented
@vobu pls review ;)

2022-04-19 13:50 UTC, vobu requested changes

2022-04-19 13:50 UTC, vobu commented on client-side-js/injectUI5.js
> +                     * JSON.stringify(circularReference, getCircularReplacer());
proper JSDoc pleae

2022-04-19 13:50 UTC, vobu commented on client-side-js/executeControlMethod.js
> +                                !(result instanceof sap.ui.core.Control)
could you src comment on the "why?" please?

2022-04-19 13:50 UTC, vobu commented on client-side-js/injectUI5.js
> +
is the next circular-thingie function still necessary/used or can its' usage be taken over by any of the above 3?

2022-04-19 13:50 UTC, vobu commented on examples/ui5-js-app/webapp/test/e2e/basic.test.js
> +    })
could you please rephrase the "its" to better communicate that these refer to the control retrieval/value api?

2022-04-19 13:50 UTC, vobu commented on src/lib/wdi5-control.ts
> +                if (responseObj) {
refactor to shorthand à la
const a = b || c

2022-04-20 06:54 UTC, vobu approved these changes

2022-04-20 06:57 UTC, merged